version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cafeteria_db
    labels:
      - "com.cafeteria.service=database"
      - "com.cafeteria.description=MySQL Database for Cafeteria System"
    environment:
      MYSQL_ROOT_PASSWORD: ab1ab2ab
      MYSQL_DATABASE: CafeteriaDB
      MYSQL_USER: cafeteria_user
      MYSQL_PASSWORD: cafeteria_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - cafeteria_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  app:
    build: .
    container_name: cafeteria_app
    labels:
      - "com.cafeteria.service=application"
      - "com.cafeteria.description=Cafeteria Management System"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: CafeteriaDB
      DB_USER: root
      DB_PASSWORD: ab1ab2ab
    networks:
      - cafeteria_network
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    profiles:
      - interactive
    restart: "no"

  app-interactive:
    build: .
    container_name: cafeteria_app_interactive
    labels:
      - "com.cafeteria.service=application"
      - "com.cafeteria.description=Cafeteria Management System - Interactive Mode"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: CafeteriaDB
      DB_USER: root
      DB_PASSWORD: ab1ab2ab
    networks:
      - cafeteria_network
    stdin_open: true
    tty: true
    command: ["java", "-cp", "/app/build:/app/lib/*", "Main"]

volumes:
  mysql_data:
    labels:
      - "com.cafeteria.volume=database-storage"

networks:
  cafeteria_network:
    driver: bridge
    labels:
      - "com.cafeteria.network=main"
