version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cafeteria_db
    environment:
      MYSQL_ROOT_PASSWORD: ab1ab2ab
      MYSQL_DATABASE: CafeteriaDB
      MYSQL_USER: cafeteria_user
      MYSQL_PASSWORD: cafeteria_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - cafeteria_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: cafeteria_app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: CafeteriaDB
      DB_USER: root
      DB_PASSWORD: ab1ab2ab
    networks:
      - cafeteria_network
    stdin_open: true
    tty: true

volumes:
  mysql_data:

networks:
  cafeteria_network:
    driver: bridge
